language: python
python:
  - "2.7.11"
  - "3.5"
  - "3.6"
  - "nightly"
install:
  - pip install -r devRequirements.txt
script:
  - coverage run -m unittest discover tests/
after_success:
  - coveralls